services:
  airflow:
    build: .
    image: airflow-custom
    container_name: airflow_container
    restart: always
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${SECRET_KEY}
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/integrated_project
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/integrated_project/olist.db
    volumes:
      - .:/opt/airflow/integrated_project
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: .
    image: airflow-custom
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${SECRET_KEY}
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/integrated_project
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/integrated_project/olist.db
    volumes:
      - .:/opt/airflow/integrated_project
    command: scheduler
